#!/bin/sh
set -ex

echo "args:" "$@"

# If using normal root, avoid changing anything.
if [ -z "$RPM_BUILD_ROOT" ] || [ "$RPM_BUILD_ROOT" = "/" ]; then
    exit 0
fi

version="$1"
if [ -z "$1" ]; then
    echo "version argument missing" >&2
    exit 2
fi

NCPUS=${RPM_BUILD_NCPUS:-1}

notefile=$(mktemp --tmpdir rpm.version.note.XXXXXXXXXX)

# include/elf/common.h:#define NT_VERSION 1       /* Contains a version string.  */

python3 -c "
name = 'gnu.package-version'.encode()
version = 'rpm:$version'.encode()
NT_VERSION = 1
ln = len(name)
lv = len(version)
pad = lambda s: [0] * ((len(s) + 4) // 4 * 4 - len(s))
note = bytes([ln+1, 0, 0, 0, lv+1, 0, 0, 0, NT_VERSION, 0, 0, 0, *name, *pad(name), *version, *pad(version)])
with open('$notefile', 'wb') as f: f.write(note)
"

cmd="objcopy --add-section .notes.package-version=$notefile --set-section-flags .notes.package-version=noload,readonly"

# Add note to all ELF binaries
find "$RPM_BUILD_ROOT" -type f \( -perm -0100 -or -perm -0010 -or -perm -0001 \) \
     \! -regex "${RPM_BUILD_ROOT}/*usr/lib/debug.*" -print0 | \
    xargs -0 -r -P$NCPUS -n32 sh -c \
	  "file \"\$@\" | awk -F: '/ELF/ {print \$1}' | xargs -I\{\} $cmd \{\}" ARG0

rm $notefile
