.TH DLOPEN\-NOTES.PY "1" "2024\-07\-23" "package\-notes" "Generated Python Manual"
.SH NAME
dlopen\-notes.py
.SH SYNOPSIS
.B dlopen\-notes.py
[-r] [-s] [-f [FEATURE1,FEATURE2]] [-h] filename [filename ...]
.SH DESCRIPTION
Read .note.dlopen notes from ELF files and report the contents.
.PP
ELF binaries store link-time dependencies in their headers, which can be parsed
by various tools. There is no machine-readable metadata about dependencies
loaded at build time via
.BR \%dlopen (3)
available by default. The ELF Dlopen Metadata specification aims to fill this
gap by defining a common format. See https://systemd.io/ELF_DLOPEN_METADATA/.
.PP
This tool allows parsing such a note, and printing out the result in various
formats.

.TP
\fBfilename\fR
Library file to extract notes from

.SH OPTIONS
.TP
\fB\-r\fR, \fB\-\-raw\fR
Show the original JSON extracted from input files

.TP
\fB\-s\fR, \fB\-\-sonames\fR
List all sonames and their priorities, one soname per line

.TP
\fB\-f\fR \fI\,[FEATURE1,FEATURE2]\/\fR, \fB\-\-features\fR \fI\,[FEATURE1,FEATURE2]\/\fR
Describe features, can be specified multiple times

.SH COMMENTS
If no option is specifed, \-\-raw is the default.
