---
# SPDX-License-Identifier: CC0-1.0
# vi: ts=2 sw=2 et:

name: Run tests
on: [pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt -y install binutils python3-pytest python3-simplejson
      - name: Run tests
        run: python3 -m pytest -v

